default: &default
  adapter: postgresql
  encoding: unicode
  host: rails_postgres
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("DATABASE_NAME") { "rails_app" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "guest" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "guest" } %>
  schema_search_path: public

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
  database: rails_test
